server:
  port: 9001
  servlet:
    context-path: /api/library
spring:
  application:
    name: library-back
    #CONFIGURACION CONEXI�N A POSTGRESQL
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/library_back
    password: admin
  jpa:
    #QUE SE ACTUALICE LA BASE DE DATOS CADA QUE HAYAN CAMBIOS
    hibernate:
      ddl-auto: create
    #MOSTRAR LAS CADENAS SQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #CARGA DE DATOS A TRAV�S DE LOS ARCHIVOS SCRIPTS
        hbm2ddl:
          charset_name: UTF-8
          import_files: scripts/role.sql, scripts/user.sql, scripts/module.sql, scripts/role_module.sql
    generate-ddl: false

# CONFIGURACIÓN PARA LA FIRMA DEL JWT
jwt:
  secret-key: 03db96010ae65496b4e7190c600f41a272d7facc1b029e64a238ee80d1b74d67
  user: AUTH-0
  duration-min: 20
refresh-token:
  duration-min: 20